### ISSUE TITLE
Error when elaborating uncrowding resolution step

### ISSUE THREAD

**Issue by NotBad4U** [ufmg-smite/carcara#50]
Versions:

- carcara version: `carcara 1.1.0 [git main 113f5a7] (current the last commit)`
 - cvc5 version: `cvc5 1.2.1-dev.144.38fcc340e5 [git 38fcc340e5 on branch main]`

Hi everyone!

When I try to `elaborate`  some files from the SMT-lib bench like this one: [QF_UF_sokoban.3.prop1_ab_br_max.smt2
](https://www.starexec.org/starexec/secure/details/benchmark.jsp?id=16376060) I got this error: [uncrowding.rs#L199](https://github.com/ufmg-smite/carcara/blob/113f5a7b64ee0443c1957d3e65ba25e385d20026/carcara/src/elaborator/uncrowding.rs#L199) :"current clause is not a subset of target clause!".

This is my output:
```bash
cargo run -- elaborate --ignore-unknown-rules --expand-let-bindings QF_UF_sokoban.3.prop1_ab_br_max.alethe QF_UF_sokoban.3.prop1_ab_br_max.smt2
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/carcara elaborate --ignore-unknown-rules --expand-let-bindings QF_UF_sokoban.3.prop1_ab_br_max.alethe QF_UF_sokoban.3.prop1_ab_br_max.smt2`
thread 'main' panicked at carcara/src/elaborator/uncrowding.rs:199:31:
current clause is not a subset of target clause!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I tried to run it with the `--uncrowd-rotate` but I got this error:
```bash
cargo run -- elaborate --uncrowd-rotate --ignore-unknown-rules --expand-let-bindings QF_UF_sokoban.3.prop1_ab_br_max.alethe QF_UF_sokoban.3.prop1_ab_br_max.smt2
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/carcara elaborate --uncrowd-rotate --ignore-unknown-rules --expand-let-bindings QF_UF_sokoban.3.prop1_ab_br_max.alethe QF_UF_sokoban.3.prop1_ab_br_max.smt2`
thread 'main' panicked at carcara/src/elaborator/uncrowding.rs:326:69:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Note that I have no idea what this option it supposed to do...I was just looking at something that deals with uncrowd 😆 ...

A more recent version of CVC5 could fix my problem, or do we have a bug in the Carcara elaborator? 🤔 
This error happens on many benchmark samples (when the proof starts to be long), which is quite blocking my progression.

**Comment by bpandreotti** [comment]
Thanks for the report! This is certainly a bug in Carcara. We generally only panic in situations that should never happen, so panics are always considered bugs. In the worst case, Carcara should at least return a nice error message. Still, in the case of resolution uncrowding, I expect a proof that checks without errors (which is the case), to be able to be uncrowded without errors. So the uncrowding algorithm is probably missing an edge case --- I will take a look.

**Comment by bpandreotti** [comment]
This has (kind of) been fixed by 91b96ccdbee2e4e2d09da22aeaa4facfe4ec32d2. The problem was that Carcara was trying to infer the pivots when elaborating, even if they were already given, and the pivots it found were incorrect. This then created some invalid state when uncrowding, which led to error you encountered. Now, we don't try to recompute the pivots, and the example you gave works fine.

Of course, the underlying problem is that the pivot inference algorithm is wrong. In particular, it does not handle correctly terms being removed, reintroduced, and later removed again. A minimal example that shows this is this proof:

```
(step t1 (cl a b) :rule hole)
(step t2 (cl (not a)) :rule hole)
(step t3 (cl (not b) a c) :rule hole)
(step t4 (cl c) :rule resolution :premises (t1 t2 t3 t2))
(step t5 (cl) :rule hole :premises (t4))
```

This causes the same error you were seeing, if the pivots are not given. I will leave this issue open while I investigate this problem further, but for now, if you make sure cvc5 gives the resolution pivots, you won't encounter this error anymore.

**Comment by NotBad4U** [comment]
Thanks @bpandreotti!

> If you make sure cvc5 gives the resolution pivots, you won't encounter this error anymore.

Is there a CVC5 option for checking this?
